"""crear tabla cargos y relacion empleados

Revision ID: df915ebf15c9
Revises: b1a58205e5b5
Create Date: 2026-05-27 14:52:47.079125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df915ebf15c9'
down_revision: Union[str, Sequence[str], None] = 'b1a58205e5b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargos_id'), 'cargos', ['id'], unique=False)
    op.add_column('empleados', sa.Column('cargo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'empleados', 'cargos', ['cargo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empleados', type_='foreignkey')
    op.drop_column('empleados', 'cargo_id')
    op.drop_index(op.f('ix_cargos_id'), table_name='cargos')
    op.drop_table('cargos')
    # ### end Alembic commands ###
